services:
  - type: web
    name: referral4referral-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    autoDeploy: true
